# Generated by Django 3.1.7 on 2021-04-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210404_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
    ]
