# Generated by Django 3.1.7 on 2021-04-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
